### ISSUE TITLE
Rever Ícone de entrada

### ISSUE THREAD

**Issue by chgp** [RedeMinas/portal#2]
criticas de parecer TV OK!

**Comment by chgp** [comment]
medir o peso com o selo da redeminas...

**Comment by joaoxavier** [comment]
Sugestão de utilizar o gatilho de interação com o Bevel(padrão rede minas). Além da locação do botão, que não conversa com a logo da RM e das retransmissões.

**Comment by buhmenezes** [comment]
Ícone mais transparente e aplicação de sombra.
