### ISSUE TITLE
layout agenda

### ISSUE THREAD

**Issue by chgp** [RedeMinas/portal#23]
Pesquisar e criar layout para aprovação do agenda

**Comment by LucasBotelho** [comment]
Comecei a projetar o layout a programação.
Estou pensando em garantir a apresentação com o método de arquitetura da informação junto das telas de navegação. Acredito que só a vinda da equipe para o teste é pouco, montar a documentação do que tem sido feito e aprovado vai ser bom para nosso futuro. Por favor comentem.

**Comment by LucasBotelho** [comment]
@buhmenezes insira aqui uns prints das telas por favor.
