### ISSUE TITLE
demandas harmonia

### ISSUE THREAD

**Issue by chgp** [RedeMinas/portal#31]
INFORMAÇÕES PARA PORTAL DO HARMONIA  - TV DIGITAL
Texto do portal geral:
O Harmonia é um programa semanal, dedicado à divulgação e à democratização da música de concerto. Nele, a vida e a obra de grandes compositores e os principais acontecimentos da cena erudita mineira atual são apresentados ao público através de reportagens com uma linguagem leve, acessível e informativa. O programa oferece ainda um momento de apreciação musical através da exibição de peças de concertos.
Equipe:
Gerusa Coelho – diretora
Clóvis Ribeiro – repórter e apresentador
Mariana Lima – repórter e apresentadora
Bruna Marta – estagiária
Felipe Ivanicska – editor e finalizador
Horários:
Domingo, 20h
Quinta-feira, 23h

PORTAL ESPECÍFICO DO HARMONIA:
Sugestão de menus:
1- EDIÇÃO DA SEMANA: Aqui, vamos produzir informações de texto e fotos sobre a edição do programa da semana. Também pensamos em colocar QRCode para vídeos extras.

2- REPERTÓRIO: Aqui, vamos disponibilizar a agenda de concertos da semana em MG

3- ESPECIAL DO MÊS: Neste espaço, produziremos conteúdo especial extra para homenagear algum evento da cena erudita (por exemplo: março é mês de aniversário de Heitor Villa-Lobos, então podemos fazer textos, fotos e QRCode com informações e vídeos sobre o compositor)
4- CONTATO: Aqui, teremos os contatos do programa: email, telefone, página de Facebook, Youtube e Instagram.

OBS:
Pegar os arquivos de identidade visual do programa com o pessoal do WEB (Lilian) ou com a ARTE (Arnaldo).

As cores do programa são verde/amarelo/lilás (ver os tons corretos no material de identidade visual produzido pela ARTE/WEB)
Temos um logotipo para o quadro REPERTÓRIO. Pegar com a ARTE (Arnaldo)... ele tem vinhetas internas dos nossos quadros.
Por hora, começaremos apenas com o quadro REPERTÓRIO no portal. Depois, acrescentaremos os demais, à medida que conseguirmos alimentar o conteúdo.

Sugestão de layout:
Gostaríamos que fosse mantido o layout de barra transparente na parte inferior da tela (largura da barra: em torno de 1/3 da tela), tal qual no portal da TV.
Gostaríamos que o menu do nosso portal fosse na lateral esquerda da barra, com ícones arredondados, que remetessem à identidade visual da nossa vinheta (favor, olhar o material visual e como são os círculos e linhas que compõe a nossa identidade visual para que possamos ter coerência nesse sentido)
A ordem dos ícones é a que está estabelecida acima: 1- Edição da semana / 2- Repertório / 3- Especial do mês / 4- Contato

**Comment by LucasBotelho** [comment]
Qual é o bug?

**Comment by chgp** [comment]
Todas demandas já foram implementadas, ajudem a revisar!

**Comment by LucasBotelho** [comment]
**Está faltando:**
1. Passar o manual de QR Codes para o programa e pegar os arquivos gerados.
2. Lembrar da entrega de conteúdo para o Portal

**Comment by LucasBotelho** [comment]
O programa já está produzindo os QR Codes e preenchendo a tabela.
As imagens estão quase prontas. Até o final do dia 2 devemos receber esse material.
