### ISSUE TITLE
Demandas - Agenda

### ISSUE THREAD

**Issue by LucasBotelho** [RedeMinas/portal#37]
**Interatividade do Programa Agenda**

Primeira Reunião. 20/01/17
Agenda: Brenda e Rodrigo - Contato: brendajornalista@gmail.com / rodrigocfcardoso@gmail.com
Ramal: 3040
Equipe Transmídia: Bruna, Carlos e Lucas

  Durante a conversa foi proposto a utilização de conteúdos da agenda cultural de BH que não vão ar. Também foi pensando sistemas de votação para o Oscar 2017.

**Tarefas:** 
**1.** Mudar a imagem do Agenda no Portal
**2.** Menu Agenda Cultural dividida por área(consultar o programa). Atualizações semanais.
**3.** Contatos com QRcode das ferramentas de redes sociais facebook e youtube no Portal
**4.** Ranking do Oscar 2017 - Votação de uma categoria por semana?
**5.** Apontamento por QR de vídeos do Hora Extra no facebook e quadro do programa no youtube

**Comment by LucasBotelho** [comment]
Cobrar as categorias de eventos para o Rodrigo do Programa Agenda

**Comment by chgp** [comment]
essas tarefas devem ser transformadas em issues...

**Comment by LucasBotelho** [comment]
OK. Eu coloquei todas aqui para ir aos poucos inserindo. Mas tudo bem, vale colocar tudo de uma vez.
