### ISSUE TITLE
Demandas - Alto Falante

### ISSUE THREAD

**Issue by LucasBotelho** [RedeMinas/portal#46]
**Interatividade do Programa Alto Falante**

Primeira Reunião. 24/01/17
Equipe Alto Falante: Sabrina e Terence
Contato: 31 3254-3043
Equipe Transmídia: Bruna, Carlos, João e Lucas

Tarefas:
1. Garimpo (conteúdo de novidades na cena musical)
2. Resumo do programa da semana, programação(textual). 
3. Agenda cultural simplificada
4. Notícias
5. Informações de utilidade pública
6. Apontamento de redes por QR Code
7. Playlist de Spotify

**Comment by LucasBotelho** [comment]
8. Enciclopédia do Rock > histórias e capas de discos

**Comment by joaoxavier** [comment]
Sugestão para a solução de seleção de conteúdo(como opção):

- resumidamente é **item do menu selecionado** e seu **respectivo conteúdo a mostra em um box de cor mais clara**

Seguem imagens:

![01](https://cloud.githubusercontent.com/assets/17200338/26466774/5a47f47e-4166-11e7-9199-3fa17c8caa88.jpg)
![02](https://cloud.githubusercontent.com/assets/17200338/26466773/5a45f160-4166-11e7-8c2b-650ab0545e39.jpg)
![03](https://cloud.githubusercontent.com/assets/17200338/26466772/5a42495c-4166-11e7-9952-58f1623e98ca.jpg)
![04](https://cloud.githubusercontent.com/assets/17200338/26466775/5a48bef4-4166-11e7-8e35-9f8128a12490.jpg)

**Comment by joaoxavier** [comment]
Reorganização de conteúdo:

- paginação nas abas dr conteúdo. Sugestão inicial foi o modelo do Harmonia.

- utilização de cores no menu.

- hierarquia de informação: troca de área de notícias contatos.

- padronização de pontos de fontes(tamanho)
