### ISSUE TITLE
Icone de entrada itinerante

### ISSUE THREAD

**Issue by chgp** [RedeMinas/portal#5]
mudanca constante do icone de posicao pode ajudar a nao manchar a tela...

**Comment by LucasBotelho** [comment]
Quais soluções de animação existentes para NCL e LUA?

**Comment by LucasBotelho** [comment]
Por favor, @joaoxavier e @buhmenezes me ajudem a pensar numa animação interessante para fazer o ícone migrar sem parecer que está com problemas técnicos.

**Comment by buhmenezes** [comment]
Uma das possibilidades é experimentar um único  PNG com todos os frames e controlar a exibição e tempo de cada um, em um espaço delimitado.

**Comment by buhmenezes** [comment]
Teste com variação de duas imagens. Imagens quadradas não ficam visualmente agradáveis. Testar com as duas imagens circulares como se fosse os dois lados da moeda.

**Comment by chgp** [comment]
implementado ab89ddf3f6d60e109535c1190406da6a5923336f
